import "./globals.css";
import { Poppins } from "next/font/google";
import Provider from "./provider";
import { Container } from "@chakra-ui/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Spendo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}antialiased`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
